spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-password: root
    data-username: root
    url: jdbc:mysql://localhost:3306/work?serverTimezone=CST&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true
    password: root
    username: root

#    上传文件配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB
  redis:
    host: localhost
